apiVersion: apps/v1
kind: Deployment
metadata:
  name: juiceshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juiceshop
  template:
    metadata:
      labels:
        app: juiceshop
        admission.datadoghq.com/cws-instrumentation.enabled: "true"
    spec:
      containers:
        - name: juiceshop
          image: ghcr.io/datadog/juice-shop:latest
          imagePullPolicy: Always
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
            - name: DD_TRACER_ENABLED
              value: "true"
            - name: DD_SERVICE
              value: "juiceshop"
            - name: DD_TRACE_DEBUG
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_APPSEC_ENABLED
              value: "true"
            - name: DD_IAST_ENABLED
              value: "true"
            - name: DD_APPSEC_SCA_ENABLED
              value: "true"
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 15
