# Ensure juiceshop is never accessible from outside the cluster
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: juiceshop-internal-only
spec:
  podSelector:
    matchLabels:
      app: juiceshop
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
