apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: playground

resources:
  - namespace.yaml
  - db-service.yaml
  - db-deployment.yaml
  - juiceshop-networkpolicy.yaml
  - juiceshop-service.yaml
  - juiceshop-deployment.yaml
